controller_manager:
  ros__parameters:
    update_rate: 200 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
    ros__parameters:
      joints:
        # - joint10
        # - joint11
        # - joint12
        - joint20
        - joint21
        - joint22
        # - joint30
        # - joint31
        # - joint32
        # - joint40
        # - joint41
        # - joint42
      command_interfaces:
        # - velocity
        - position
      state_interfaces:
        - position
        - velocity

        # - effort
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      # gains.front_left_knee_joint: 1.0
